@startuml

top to bottom direction
' left to right direction

skinparam shadowing false
skinparam monochrome true

class PyELMT{
    id
    type
    description*
    update()
}

class AbstractELMT{
    name
}

class PhysicalELMT{
    name
    material: Material
}

Interface Mongo{
    mongo_document
    export_mongo(): MongoDB document
    import_mongo(MongoDB document)
'    - attribute_check()
}

Interface OpenBrIM{
    export_openbrim(): OpenBrIM file
    import_openbrim(OpenBrIM file)
'    - attribute_check()
}

Interface OpenBrIM_fem{
    openbrim_fem_elmt
}

Interface OpenBrIM_geo{
    openbrim_geo_elmt
}

PyELMT <|-- AbstractELMT
PyELMT <|-- PhysicalELMT
OpenBrIM_fem <|-- AbstractELMT
OpenBrIM_fem <|-- PhysicalELMT
OpenBrIM_geo <|-- PhysicalELMT

OpenBrIM <|-- OpenBrIM_fem
OpenBrIM <|-- OpenBrIM_geo
Mongo <|-- PyELMT

@enduml
