@startuml

' left to right direction

skinparam shadowing false
skinparam monochrome true

class PyELMT{
    id
    type
    description*
    update()
}

class AbstractELMT{
    name
}
PyELMT <|-- AbstractELMT

class PhysicalELMT{
    name
    material: Material
}
PyELMT <|-- PhysicalELMT

class FENode{
    x: Parameter
    y: Parameter
    z: Parameter
    tx: Parameter
    ty: Parameter
    tz: Parameter
    rx: Parameter
    ry: Parameter
    rz: Parameter
}
class Section{
    shape_node_list[]
}
class Material{
    type
    property_list[]: Parameter
}


AbstractELMT <|-- Section
AbstractELMT <|-- Material
AbstractELMT <|-- FENode


class Beam{
    fenode1: FENode
    fenode2: FENode
    section: Section
}
class Surface{
    fenode[]: FENode
    thickness: Parameter
}
class Volume{
    fenode[]: FENode
}
PhysicalELMT <|-- Beam
PhysicalELMT <|-- Surface
PhysicalELMT <|-- Volume

@enduml
