@startuml

top to bottom direction
' left to right direction

skinparam shadowing false
skinparam monochrome true


Interface toMongo{
    set_mongo_document()
    get_mongo_document()
    - argument_check()
}

class PyELMT{
    id
    type
    description*
    update()
}

class AbstractELMT{
    name
}

class PhysicalELMT{
    name
    material: Material
}

' hide PhysicalELMT circle

Interface toOpenBrIM{
    openbrim_element: XML element
    set_openbrim_element()
    get_openbrim_element()
    - argument_check()
}

Interface has_OpenBrIM_fem{
    openbrim_fem_elmt()
}

Interface has_OpenBrIM_geo{
    openbrim_geo_elmt()
}

PyELMT <|-- AbstractELMT
PyELMT <|-- PhysicalELMT
has_OpenBrIM_fem <|-- AbstractELMT
has_OpenBrIM_fem <|-- PhysicalELMT
has_OpenBrIM_geo <|-- PhysicalELMT

toOpenBrIM <|-- has_OpenBrIM_fem
toOpenBrIM <|-- has_OpenBrIM_geo
toMongo -- PyELMT

@enduml
