@startuml
participant Bridge as br
participant Python as py
participant OpenBrIM as ob
participant MongoDB as mg

br ->py: new BrIM model
py -> ob: create ParamML file
py -> mg: create Mongo document
note over ob: OpenBrIM APP view
note over ob: OpenBrIM examination
ob --> py: update attributes
py --> ob: re-create ParamML file

py -> mg: store
@enduml
